;# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Happy Ivy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Happy Ivy
    pod ‘JTAppleCalendar’ , ‘~>7.0’
    pod ‘Spring’, :git => 'https://github.com/MengTo/Spring.git'
    pod ‘RealmSwift’
    pod ‘Charts’
end
